import Head from "next/head";
import Link from "next/dist/client/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "remixicon/fonts/remixicon.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <link
          href=" https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css "
          rel=" stil sayfası "
        />
        <title>Ahmet Talha Telli</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ahmet Talha Telli</h1>

        <p className={styles.description}>
          Computer Engineering &nbsp;
          <code className={styles.code}> Frontend Developer</code>
        </p>

        <div className={styles.grid}>
          <Link href="https://github.com/talhatelli">
            <i
              title="Github"
              className="ri-github-fill"
              style={{
                color: "white",
                fontSize: "100px",
                height: " 100px",
                fill: " #333",
                minHeight: "100vh",
                padding: "4rem 0",
                flex: "1",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            ></i>
          </Link>
          <Link href="https://www.instagram.com/ahmet_talha_telli/">
            <i
              title="Instegram"
              className="ri-instagram-line"
              style={{
                color: "white",

                fontSize: "100px",
                height: " 100px",
                fill: " #333",
                minHeight: "100vh",
                padding: "4rem 0",
                flex: "1",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            ></i>
          </Link>

          <Link href="https://www.linkedin.com/in/ahmet-talha-telli-09473a230/">
            <i
              title="Linkedin"
              className="ri-linkedin-box-fill"
              style={{
                color: "white",
                fontSize: "100px",
                height: " 100px",
                fill: " #333",
                minHeight: "100vh",
                padding: "4rem 0",
                flex: "1",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            ></i>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Devoloper by Ahmet Talha <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}

{
  /* <a href="https://nextjs.org/learn" className={styles.card}>
<h2>Learn &rarr;</h2>
<p>Learn about Next.js in an interactive course with quizzes!</p>
</a> */
}
