import Head from "next/head";
import Footer from "./component/footerComponent";
import IconLink from "./component/iconLink";
import styles from "../styles/Home.module.css";
import "remixicon/fonts/remixicon.css";
import Layout from "./component/header/layout";
export default function Home() {
  return (
    <div>
      <Layout />
      <div className={styles.container}>
        <Head>
          <link
            href=" https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css "
            rel=" stil sayfası "
          />
          <title>Ahmet Talha Telli</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Ahmet Talha Telli</h1>
          <p className={styles.description}>
            Computer Engineering &nbsp;
            <code className={styles.code}> Frontend Developer</code>
          </p>{" "}
          <IconLink />
        </main>
        <Footer />
      </div>
    </div>
  );
}
